theme = "blowfish"
baseURL = "https://insidemordecai.com"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

enableGitInfo = true

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = "G-R5NDGF0KV2"

[params.author]
  name = "Mordecai Kipng'etich"
  email = "mk@insidemordecai.com"
  image = "img/profile.png"
  headline = "welcome to my corner of the internet about everything"
  bio = "not from Regular Show"
  links = [
    { email = "mailto:mk@insidemordecai.com"},
    { spotify = "https://open.spotify.com/user/jv19tenfbkqd9so7369kfvwxa?si=29415d195d8d41f4"},
    { bluesky = "https://bsky.app/profile/insidemordecai.com" },
    { threads = "https://threads.net/insidemordecai"},
    { twitter = "https://x.com/insidemordecai" },
    { github = "https://github.com/insidemordecai" },
    # { linkedin = "https://linkedin.com/in/insidemordecai" },
    { goodreads = "https://goodreads.com/insidemordecai"}
  ]

[permalinks]
  posts = '/:slug/' # for cleaner links
  attic = '/:slug/'

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
